# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
import genpassword
import addaccount
import settings
from library.api import updateVault
class Ui_MainWindow(QtWidgets.QDialog):
    
    def setupUi(self, Dialog, session, parent, app):
        self.currentsession= session
        self.parentWindow =parent
        self.Dialog = Dialog
        app.focusChanged.connect(self.changedfocus)
        self.app = app
        Dialog.setObjectName("Dialog")
        Dialog.resize(670, 487)
        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.btnAddAccount = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddAccount.setGeometry(QtCore.QRect(310, 10, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnAddAccount.setFont(font)
        self.btnAddAccount.setObjectName("btnAddAccount")
        self.btnAddAccount.clicked.connect(self.OpenAddAccountWindow)
        self.btnSettings = QtWidgets.QPushButton(self.centralwidget)
        self.btnSettings.setGeometry(QtCore.QRect(610, 10, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnSettings.setFont(font)
        self.btnSettings.setObjectName("btnSettings")
        self.btnSettings.setIconSize(QtCore.QSize(40, 30))
        self.btnSettings.clicked.connect(self.OpenSettingsWindow)
        self.btnSettings.setText("Settings")
        self.btnLock = QtWidgets.QPushButton(self.centralwidget)
        self.btnLock.setGeometry(QtCore.QRect(490, 10, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnLock.setFont(font)
        self.btnLock.setStyleSheet("")
        self.btnLock.setObjectName("btnLock")
        self.btnLock.clicked.connect(self.Lock)
        self.lnSearchAccount = QtWidgets.QLineEdit(self.centralwidget)
        self.lnSearchAccount.setGeometry(QtCore.QRect(10, 10, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lnSearchAccount.setFont(font)
        self.lnSearchAccount.setObjectName("lnSearchAccount")
        self.lnSearchAccount.textChanged.connect(self.searchOnChange)
        self.scroll1 = QtWidgets.QScrollArea(self.centralwidget)
        self.scroll1.setGeometry(QtCore.QRect(370, 70, 295, 410))
        self.scroll1.setWidgetResizable(True)
        self.scroll1.setObjectName("scroll1")
        self.scrollContent1 = QtWidgets.QWidget()
        self.scrollContent1.setGeometry(QtCore.QRect(0, 0, 259, 78))
        self.scrollContent1.setObjectName("scrollContent1")
        self.gridLayout1 = QtWidgets.QGridLayout(self.scrollContent1)
        self.gridLayout1.setContentsMargins(0, 0, 0, 0)
        self.gridLayout1.setSpacing(0)
        self.gridLayout1.setObjectName("gridLayout1")
        self.scroll2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scroll2.setGeometry(QtCore.QRect(10, 70, 331, 410))
        self.scroll2.setWidgetResizable(True)
        self.scroll2.setObjectName("scroll2")
        self.scrollContent2 = QtWidgets.QWidget()
        self.scrollContent2.setGeometry(QtCore.QRect(0, 0, 329, 78))
        self.scrollContent2.setObjectName("scrollContent2")
        self.gridLayout2 = QtWidgets.QGridLayout(self.scrollContent2)
        self.gridLayout2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout2.setSpacing(0)
        self.gridLayout2.setObjectName("gridLayout2")
        self.generateAccountLabels()
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Team Yolo Password Manager"))
        self.btnAddAccount.setText(_translate("Dialog", "Add account"))
        self.btnLock.setText(_translate("Dialog", "Lock"))
        self.lnSearchAccount.setPlaceholderText(_translate("Dialog", "Search account"))

    class ClickLabel(QtWidgets.QLabel):
        clicked = QtCore.pyqtSignal()
        def mousePressEvent(self, event):
            self.clicked.emit()
            QtWidgets.QLabel.mousePressEvent(self, event)

    def Lock(self):
        self.parentWindow.show()
        self.app.focusChanged.disconnect()
        self.lockTimer.deleteLater()
        self.Dialog.close()

    def deleteAllwidgetinGridLayout(self,gridlayoutnumber,startfrom):
        #delete all items inside gridlayout
        if gridlayoutnumber==1:
            for i in reversed(range(self.gridLayout1.count())):
                self.gridLayout1.itemAt(startfrom).widget().setParent(None)
        elif gridlayoutnumber==2:
            for i in reversed(range(self.gridLayout2.count())):
                if(i<=startfrom):
                    break
                self.gridLayout2.itemAt(startfrom).widget().setParent(None)

    def focusOnInfo(self,searchterm="",searching=False):
        label = self.sender()
        if label.styleSheet() == '':
            for i in range(len(self.currentsession.getUserAccountNames())):
                if searching==False:
                    if label.objectName() == "lblAccountName%d" % i:
                        #selected
                        label.setStyleSheet("background-color: rgb(24, 25, 71);}")
                    else:
                        #not selected
                        newlabel = self.centralwidget.findChild(self.ClickLabel, "lblAccountName%d" % i)
                        newlabel.setStyleSheet("")
                else:
                    if searchterm in self.currentsession.getUserAccountNames()[i].lower() :
                        if label.objectName() == "lblAccountName%d" % i:
                            #selected
                            label.setStyleSheet("background-color: rgb(24, 25, 71);}")
                        else:
                            #not selected
                            newlabel = self.centralwidget.findChild(self.ClickLabel, "lblAccountName%d" % i)
                            newlabel.setStyleSheet("")
        else:
            label.setStyleSheet("")
        ID = label.objectName().replace("lblAccountName","")
        self.generateInfoLabels(self.currentsession.getUserAccount(self.currentsession.getUserAccountNames()[int(ID)]))
        
    def OnClickRevealOrHide(self,text):
        newtext = ""
        for x in range(len(text)):
            newtext +=text[x]
            if x % 28 == 0 and x!=0:
                newtext+="<br>"
        label = self.sender()
        if label.text() == "<span style='font-size:12pt; font-weight:600; color:#c392f7;'>Password</span><br><span style=' font-size:10pt; font-weight:600; color:#ffffff;'>***************</span>":
            label.setText(
            "<span style='font-size:12pt; font-weight:600; color:#c392f7;'>Password</span><br><span style=' font-size:10pt; font-weight:600; color:#ffffff;'>%s</span>"%newtext)
            label.setToolTip("Click to Hide!")
        else:
            label.setToolTip("Click to Reveal!")
            label.setText("<span style='font-size:12pt; font-weight:600; color:#c392f7;'>Password</span><br><span style=' font-size:10pt; font-weight:600; color:#ffffff;'>***************</span>")

    def deleteAccount(self,item):
        qm = QtWidgets.QMessageBox()
        ret = qm.warning(self,'Delete Account', "Are you sure you want to delete \""+item+"\"?", qm.Yes | qm.Cancel)
        if ret == qm.Yes:
            self.currentsession.deleteAccount(item)
            updateVault(self.currentsession)
            self.generateAccountLabels()
            self.deleteAllwidgetinGridLayout(2,0)

    def editSavedetails(self,item,newAN,newUN,newP,Info):
        ANupdate = False
        UNupdate = False
        Pupdate = False
        OriginalItem = item
        TbcItem = item
        Error = False
        #check not empty
        ErrorMessage = ""
        if newAN and newUN and newP:
            #check password is >8 and <64
            if len(newP) >=8 and len(newP)<=64:
                if newAN != OriginalItem.name :
                    if not self.currentsession.checkAccountExists(newAN):
                        TbcItem.name = newAN
                        ANupdate = True
                    else:
                        Error = True
                        ErrorMessage+="This AccountName already exists<br>"
                if OriginalItem.username != newUN:
                            TbcItem.username = newUN
                            UNupdate = True
                if OriginalItem.password != newP:
                            TbcItem.password = newP
                            Pupdate = True
                if (Pupdate or UNupdate or ANupdate) and Error==False:
                            if ANupdate:
                                item.name = TbcItem.name
                            if UNupdate:
                                item.username = TbcItem.username
                            if Pupdate:
                                item.password = TbcItem.password
                            updateVault(self.currentsession)
                            self.generateInfoLabels(self.currentsession.getUserAccount(item.name))
                            self.generateAccountLabels()
                else:
                    Info.setText(ErrorMessage+"No changes made.")

            else:
                Info.setText("Password must be <br>1)Less than or equal to 64 characters.<br>2)More than or equal to 8 characters.")
        else:
            Info.setText("The above inputs must not be empty.")

    def OpenAddAccountWindow(self):
                self.w = addaccount.Ui_Form()
                self.w.Dialog = QtWidgets.QDialog(None, QtCore.Qt.WindowCloseButtonHint)
                self.w.Dialog.setFixedSize(410, 385)
                self.w.setupUi(self.w,self.currentsession)
                self.w.emitter.connect(self.onAccountCreated)
                self.w.Dialog.show()

    def OpenSettingsWindow(self):
                self.w = settings.Settings()
                self.w.Dialog = QtWidgets.QDialog(None, QtCore.Qt.WindowCloseButtonHint)
                self.w.Dialog.setFixedSize(322, 160)
                self.w.setupUi(self.w.Dialog,self.currentsession)
                self.w.Dialog.show()  

    def OpenGenPassWindow(self): 
                self.w = genpassword.Ui_GeneratePassword()
                self.w.Dialog = QtWidgets.QDialog(None, QtCore.Qt.WindowCloseButtonHint)
                self.w.Dialog.setFixedSize(410, 203)
                self.w.setupUi(self.w.Dialog)
                self.w.mainpassword.connect(self.setGeneratedPassword)
                self.w.Dialog.show()

    def searchOnChange(self):
        self.generateAccountLabels(self.lnSearchAccount.text(),True)
        self.deleteAllwidgetinGridLayout(2,0)
        
    def onAccountCreated(self,accountname):
                self.generateAccountLabels()
                
    def setGeneratedPassword(self,password):
        if self.leEditPassword.echoMode()==QtWidgets.QLineEdit.Password:
            self.leEditPassword.setEchoMode(QtWidgets.QLineEdit.Normal)
            self.btnPasswordRH.setText("Conceal")
        self.leEditPassword.setText(password)

    def OnClickLeRevealOrHide(self,lineEdit):
        label = self.sender()
        if lineEdit.echoMode()==QtWidgets.QLineEdit.Normal:
            lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
            label.setText("Reveal")
        else:
            lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
            label.setText("Conceal")

    def copyClipBoard(self, text):
        cb = QtGui.QGuiApplication.clipboard()
        cb.clear(mode=cb.Clipboard)
        cb.setText(text, mode=cb.Clipboard)
        self.clipBoardTimer=QtCore.QTimer()
        self.clipBoardTimer.start(self.currentsession.clipboard)
        self.clipBoardTimer.timeout.connect(self.clearClipBoard)

    def clearClipBoard(self):
        cb = QtGui.QGuiApplication.clipboard()
        cb.clear(mode=cb.Clipboard)
        self.clipBoardTimer.stop()
    
    def changedfocus(self, old, now):
        self.lockTimer=QtCore.QTimer()
        if now == None:
            if self.currentsession.lock>0:
                if not self.lockTimer.isActive():
                    
                    self.lockTimer.start(self.currentsession.lock)
                    self.lockTimer.timeout.connect(self.Lock)
        else:
                self.lockTimer.stop()

    def generateEditInfoLabels(self,items):
        self.deleteAllwidgetinGridLayout(2,0)
        self.btnSave = QtWidgets.QPushButton()
        self.btnSave.setGeometry(QtCore.QRect(280, 210, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSave.setFont(font)
        self.btnSave.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnSave.setStyleSheet("")
        self.btnSave.setObjectName("btnSave")
        self.btnSave.clicked.connect(lambda: self.editSavedetails(items,self.leEditAccountName.text(),self.leEditUsername.text(),self.leEditPassword.text(),self.lblEditMessage))
        self.gridLayout2.addWidget(self.btnSave, 0, 0, 1, 1)
        self.deleteAllwidgetinGridLayout(2,0)
        self.btnCancel = QtWidgets.QPushButton()
        self.btnCancel.setGeometry(QtCore.QRect(280, 210, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnCancel.setFont(font)
        self.btnCancel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnCancel.setStyleSheet("")
        self.btnCancel.setObjectName("btnCancel")
        self.btnCancel.clicked.connect(lambda: self.generateInfoLabels(self.currentsession.getUserAccount(items.name)))
        self.gridLayout2.addWidget(self.btnCancel, 0, 2, 1, 1)
        self.lblSpacer = QtWidgets.QLabel()
        self.lblSpacer.setObjectName("lblSpacer")
        self.lblSpacer.setStyleSheet("")
        self.lblSpacer.setGeometry(QtCore.QRect(0, 0, 10, 10))
        self.gridLayout2.addWidget(self.lblSpacer, 1, 0, 1, 5)
        self.lblEditAccountName = QtWidgets.QLabel()
        self.lblEditAccountName.setGeometry(QtCore.QRect(10, 160, 329, 49))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblEditAccountName.setFont(font)
        self.lblEditAccountName.setFrameShape(QtWidgets.QFrame.Box)
        self.lblEditAccountName.setAlignment(QtCore.Qt.AlignLeft)
        self.lblEditAccountName.setObjectName("lblEditAccountName")
        self.gridLayout2.addWidget(self.lblEditAccountName, 2, 0, 1, 5)
        self.leEditAccountName = QtWidgets.QLineEdit()
        self.leEditAccountName.setGeometry(QtCore.QRect(10, 160, 329, 49))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(9)
        self.leEditAccountName.setFont(font)
        self.leEditAccountName.setObjectName("leEditAccountName")
        self.leEditAccountName.setMaxLength(64)
        self.gridLayout2.addWidget(self.leEditAccountName, 3, 0, 1, 5)
        self.lblEditUsername = QtWidgets.QLabel()
        self.lblEditUsername.setGeometry(QtCore.QRect(10, 210, 269, 49))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblEditUsername.setFont(font)
        self.lblEditUsername.setFrameShape(QtWidgets.QFrame.Box)
        self.lblEditUsername.setAlignment(QtCore.Qt.AlignLeft)
        self.lblEditUsername.setObjectName("lblEditUsername")
        self.lblEditUsername.setTextFormat(QtCore.Qt.RichText)
        self.gridLayout2.addWidget(self.lblEditUsername, 4, 0, 1, 5)
        self.leEditUsername = QtWidgets.QLineEdit()
        self.leEditUsername.setGeometry(QtCore.QRect(10, 160, 329, 49))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(9)
        self.leEditUsername.setFont(font)
        self.leEditUsername.setObjectName("leEditUsername")
        self.leEditUsername.setMaxLength(64)
        self.gridLayout2.addWidget(self.leEditUsername, 5, 0, 1, 5)
        self.lblEditPassword = self.ClickLabel()
        self.lblEditPassword.setGeometry(QtCore.QRect(10, 260, 191, 49))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblEditPassword.setFont(font)
        self.lblEditPassword.setFrameShape(QtWidgets.QFrame.Box)
        self.lblEditPassword.setAlignment(QtCore.Qt.AlignLeft)
        self.lblEditPassword.setObjectName("lblEditPassword")
        self.lblEditPassword.setTextFormat(QtCore.Qt.RichText)
        self.gridLayout2.addWidget(self.lblEditPassword, 6, 0, 1, 5)
        self.leEditPassword = QtWidgets.QLineEdit()
        self.leEditPassword.setGeometry(QtCore.QRect(10, 160, 329, 49))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(9)
        self.leEditPassword.setFont(font)
        self.leEditPassword.setObjectName("leEditPassword")
        self.leEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.leEditPassword.setMaxLength(64)
        self.gridLayout2.addWidget(self.leEditPassword, 7, 0, 1, 5)
        self.btnPasswordRH = QtWidgets.QPushButton()
        self.btnPasswordRH.setGeometry(QtCore.QRect(280, 260, 61, 51))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(9)
        self.btnPasswordRH.setFont(font)
        self.btnPasswordRH.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnPasswordRH.setStyleSheet("")
        self.btnPasswordRH.setIconSize(QtCore.QSize(50, 40))
        self.btnPasswordRH.setObjectName("btnPasswordRH")
        self.btnPasswordRH.clicked.connect(lambda: self.OnClickLeRevealOrHide(self.leEditPassword))
        self.gridLayout2.addWidget(self.btnPasswordRH, 8, 0, 1, 1)
        self.btnPasswordRandomGenerate = QtWidgets.QPushButton()
        self.btnPasswordRandomGenerate.setGeometry(QtCore.QRect(280, 260, 61, 51))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(9)
        self.btnPasswordRandomGenerate.setFont(font)
        self.btnPasswordRandomGenerate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnPasswordRandomGenerate.setStyleSheet("")
        self.btnPasswordRandomGenerate.setIconSize(QtCore.QSize(50, 40))
        self.btnPasswordRandomGenerate.setObjectName("btnPasswordRandomGenerate")
        self.btnPasswordRandomGenerate.clicked.connect(self.OpenGenPassWindow)
        self.gridLayout2.addWidget(self.btnPasswordRandomGenerate, 8, 1, 1, 1)
        self.lblSpacer = QtWidgets.QLabel()
        self.lblSpacer.setObjectName("lblSpacer")
        self.lblSpacer.setStyleSheet("")
        self.lblSpacer.setGeometry(QtCore.QRect(0, 0, 10, 10))
        self.gridLayout2.addWidget(self.lblSpacer, 9, 0, 1, 5)
        self.lblEditMessage = QtWidgets.QLabel()
        self.lblEditMessage.setGeometry(QtCore.QRect(10, 160, 329, 49))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblEditMessage.setFont(font)
        self.lblEditMessage.setAlignment(QtCore.Qt.AlignLeft)
        self.lblEditMessage.setObjectName("lblEditMessage")
        self.lblEditMessage.setTextFormat(QtCore.Qt.RichText)
        self.gridLayout2.addWidget(self.lblEditMessage, 10, 0, 1, 5)
        self.lblSpacer = QtWidgets.QLabel()
        self.lblSpacer.setObjectName("lblSpacer")
        self.lblSpacer.setStyleSheet("")
        self.lblSpacer.setGeometry(QtCore.QRect(0, 0, 10, 10))
        self.gridLayout2.addWidget(self.lblSpacer, 11, 0, 1, 5)
        self.lblEditAccountName.setText("Account Name")
        self.lblEditUsername.setText("\nUsername\n")
        self.lblEditPassword.setText("\nPassword\n")
        self.btnPasswordRH.setText("Reveal")
        self.btnPasswordRandomGenerate.setText("Generate Password")
        self.leEditAccountName.setText(items.name)
        self.leEditUsername.setText(items.username)
        self.leEditPassword.setText(items.password)
        self.btnSave.setText("\nSave\n")
        self.btnCancel.setText("\nCancel\n")
        self.scrollContent2.setLayout(self.gridLayout2)
        self.scroll2.setWidget(self.scrollContent2)

    def generateInfoLabels(self,items):
        self.deleteAllwidgetinGridLayout(2,0)
        self.btnEdit = QtWidgets.QPushButton()
        self.btnEdit.setGeometry(QtCore.QRect(280, 210, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnEdit.setFont(font)
        self.btnEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnEdit.setStyleSheet("")
        self.btnEdit.setObjectName("btnEdit")
        self.btnEdit.clicked.connect(lambda :self.generateEditInfoLabels(items))
        self.gridLayout2.addWidget(self.btnEdit, 0, 0, 1, 1)
        self.btnDelete = QtWidgets.QPushButton()
        self.btnDelete.setGeometry(QtCore.QRect(280, 210, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDelete.setFont(font)
        self.btnDelete.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnDelete.setStyleSheet("")
        self.btnDelete.setObjectName("btnDelete")
        self.btnDelete.clicked.connect(lambda :self.deleteAccount(items.name))
        self.gridLayout2.addWidget(self.btnDelete, 0, 2, 1, 1)
        self.lblSpacer = QtWidgets.QLabel()
        self.lblSpacer.setObjectName("lblSpacer")
        self.lblSpacer.setStyleSheet("")
        self.lblSpacer.setGeometry(QtCore.QRect(0, 0, 10, 10))
        self.gridLayout2.addWidget(self.lblSpacer, 1, 0, 1, 5)
        self.lblInfoAccountName = QtWidgets.QLabel()
        self.lblInfoAccountName.setGeometry(QtCore.QRect(10, 160, 329, 49))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblInfoAccountName.setFont(font)
        self.lblInfoAccountName.setFrameShape(QtWidgets.QFrame.Box)
        self.lblInfoAccountName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblInfoAccountName.setObjectName("lblInfoAccountName")
        self.gridLayout2.addWidget(self.lblInfoAccountName, 2, 0, 1, 5)
        self.lblInfoUsername = QtWidgets.QLabel()
        self.lblInfoUsername.setGeometry(QtCore.QRect(10, 210, 269, 49))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblInfoUsername.setFont(font)
        self.lblInfoUsername.setFrameShape(QtWidgets.QFrame.Box)
        self.lblInfoUsername.setAlignment(QtCore.Qt.AlignLeft)
        self.lblInfoUsername.setObjectName("lblInfoUsername")
        self.lblInfoUsername.setTextFormat(QtCore.Qt.RichText)
        self.gridLayout2.addWidget(self.lblInfoUsername, 3, 0, 1, 4)
        self.btnUserCC = QtWidgets.QPushButton()
        self.btnUserCC.setGeometry(QtCore.QRect(280, 210, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnUserCC.setFont(font)
        self.btnUserCC.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnUserCC.setStyleSheet("")
        self.btnUserCC.setObjectName("btnUserCC")
        self.btnUserCC.clicked.connect(lambda: self.copyClipBoard(items.username))
        self.gridLayout2.addWidget(self.btnUserCC, 3, 4, 1, 1)
        self.lblInfoPassword = self.ClickLabel()
        self.lblInfoPassword.setGeometry(QtCore.QRect(10, 260, 191, 49))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblInfoPassword.setFont(font)
        self.lblInfoPassword.setFrameShape(QtWidgets.QFrame.Box)
        self.lblInfoPassword.setAlignment(QtCore.Qt.AlignLeft)
        self.lblInfoPassword.setObjectName("lblInfoPassword")
        self.lblInfoPassword.setTextFormat(QtCore.Qt.RichText)
        self.gridLayout2.addWidget(self.lblInfoPassword, 4, 0, 1, 4)
        self.lblInfoPassword.setToolTip("Click to Reveal!")
        self.lblInfoPassword.clicked.connect(lambda: self.OnClickRevealOrHide(items.password))
        self.btnPasswordCC = QtWidgets.QPushButton()
        self.btnPasswordCC.setGeometry(QtCore.QRect(280, 260, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnPasswordCC.setFont(font)
        self.btnPasswordCC.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnPasswordCC.setStyleSheet("")
        self.btnPasswordCC.setIconSize(QtCore.QSize(50, 40))
        self.btnPasswordCC.setObjectName("btnPasswordCC")
        self.gridLayout2.addWidget(self.btnPasswordCC, 4, 4, 1, 1)
        self.lblSpacer = QtWidgets.QLabel()
        self.lblSpacer.setObjectName("lblSpacer")
        self.lblSpacer.setStyleSheet("")
        self.lblSpacer.setGeometry(QtCore.QRect(0, 0, 10, 10))
        self.gridLayout2.addWidget(self.lblSpacer, 5, 0, 10, 5)
        self.btnUserCC.setText("\nCopy\n")
        self.btnPasswordCC.setText("\nCopy\n")
        self.btnPasswordCC.clicked.connect(lambda: self.copyClipBoard(items.password))
        self.lblInfoAccountName.setText("\n%s\n"%items.name)
        self.lblInfoUsername.setText("<span style='font-size:12pt; font-weight:600; color:#c392f7;'>Username</span><br><span style=' font-size:10pt; font-weight:600; color:#ffffff;'>%s</span>"%items.username)
        self.lblInfoPassword.setText("<span style='font-size:12pt; font-weight:600; color:#c392f7;'>Password</span><br><span style=' font-size:10pt; font-weight:600; color:#ffffff;'>***************</span>")
        self.btnEdit.setText("\nEdit\n")
        self.btnDelete.setText("\nDelete\n")
        self.scrollContent2.setLayout(self.gridLayout2)
        self.scroll2.setWidget(self.scrollContent2)

    def generateAccountLabels(self, searchName="", searching=False):
        if(searchName==""):
            searching=False
        self.deleteAllwidgetinGridLayout(1,0)
        counter = 0
        if len(self.currentsession.getUserAccountNames()) >0:
            for i in range(len(self.currentsession.getUserAccountNames())):
                if searching == False:
                    self.lblAccountName = self.ClickLabel()
                    self.lblAccountName.setGeometry(QtCore.QRect(390, 160, 189, 29))
                    font = QtGui.QFont()
                    font.setPointSize(12)
                    self.lblAccountName.setFont(font)
                    self.lblAccountName.setFrameShape(QtWidgets.QFrame.Box)
                    self.lblAccountName.setAlignment(QtCore.Qt.AlignLeft)
                    self.lblAccountName.setObjectName("lblAccountName%d" % i)
                    self.lblAccountName.setStyleSheet("")
                    self.lblAccountName.clicked.connect(lambda: self.focusOnInfo())
                    self.gridLayout1.addWidget(self.lblAccountName, counter, 0, 1, 3)
                    counter = counter + 1
                    self.lblAccountName.setText("Account Name\n%s"%self.currentsession.getUserAccountNames()[i])
                else:
                    if searchName in self.currentsession.getUserAccountNames()[i].lower():
                        self.lblAccountName = self.ClickLabel()
                        self.lblAccountName.setGeometry(QtCore.QRect(390, 160, 189, 29))
                        font = QtGui.QFont()
                        font.setPointSize(12)
                        self.lblAccountName.setFont(font)
                        self.lblAccountName.setFrameShape(QtWidgets.QFrame.Box)
                        self.lblAccountName.setAlignment(QtCore.Qt.AlignLeft)
                        self.lblAccountName.setObjectName("lblAccountName%d" % i)
                        self.lblAccountName.setStyleSheet("")
                        self.lblAccountName.clicked.connect(lambda: self.focusOnInfo(searchName, True))
                        self.gridLayout1.addWidget(self.lblAccountName, counter, 0, 1, 3)
                        counter = counter + 1
                        self.lblAccountName.setText("Account Name\n%s"%self.currentsession.getUserAccountNames()[i])

            while counter<10:
                self.lblResSpacer = QtWidgets.QLabel()
                self.lblResSpacer.setObjectName("lblResSpacer" + str(i))
                self.lblResSpacer.setStyleSheet("background-color: rgb(100, 100, 100);")
                self.lblResSpacer.setGeometry(QtCore.QRect(0, 0, 10, 10))
                self.gridLayout1.addWidget(self.lblResSpacer, counter, 0, 1, 3)
                counter = counter + 1
        self.scrollContent1.setLayout(self.gridLayout1)
        self.scroll1.setWidget(self.scrollContent1)
