# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\geral\Desktop\CZ4010\Final2\CZ4010-Project-PasswordManager\gui\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(588, 426)
        self.lblTitle = QtWidgets.QLabel(Dialog)
        self.lblTitle.setGeometry(QtCore.QRect(70, 40, 461, 61))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(20)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        self.lblUsername = QtWidgets.QLabel(Dialog)
        self.lblUsername.setGeometry(QtCore.QRect(100, 130, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lblUsername.setFont(font)
        self.lblUsername.setObjectName("lblUsername")
        self.lblPassword = QtWidgets.QLabel(Dialog)
        self.lblPassword.setGeometry(QtCore.QRect(100, 170, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lblPassword.setFont(font)
        self.lblPassword.setObjectName("lblPassword")
        self.leUsername = QtWidgets.QLineEdit(Dialog)
        self.leUsername.setGeometry(QtCore.QRect(230, 130, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.leUsername.setFont(font)
        self.leUsername.setObjectName("leUsername")
        self.lePassword = QtWidgets.QLineEdit(Dialog)
        self.lePassword.setGeometry(QtCore.QRect(230, 170, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lePassword.setFont(font)
        self.lePassword.setObjectName("lePassword")
        self.btnLogin = QtWidgets.QPushButton(Dialog)
        self.btnLogin.setGeometry(QtCore.QRect(250, 220, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnLogin.setFont(font)
        self.btnLogin.setObjectName("btnLogin")
        self.btnSignup = QtWidgets.QPushButton(Dialog)
        self.btnSignup.setGeometry(QtCore.QRect(240, 320, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnSignup.setFont(font)
        self.btnSignup.setObjectName("btnSignup")
        self.lblMessage = QtWidgets.QLabel(Dialog)
        self.lblMessage.setGeometry(QtCore.QRect(10, 370, 571, 51))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        self.lblMessage.setFont(font)
        self.lblMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMessage.setObjectName("lblMessage")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblTitle.setText(_translate("Dialog", "Team YOLO PASSWORD MANAGER"))
        self.lblUsername.setText(_translate("Dialog", "User name:"))
        self.lblPassword.setText(_translate("Dialog", "Password:"))
        self.btnLogin.setText(_translate("Dialog", "Login"))
        self.btnSignup.setText(_translate("Dialog", "Sign Up"))
        self.lblMessage.setText(_translate("Dialog", "Signup failed."))
